#!/bin/sh

mir_demo_server_minimal --file /run/mir_socket --vt 1 $@ &

# Can't use --arw-file with vivid version of mir_demo_server_minimal...
while ! [ -S /run/mir_socket ]; do
    sleep 0.1
done
chmod a+rw /run/mir_socket

wait
