name: @PACKAGE@
version: @VERSION@
architecture: @ARCH@
type: framework
services:
  - name: system-compositor
    description: "system compositor"
    start: bin/usc
integration:
  framework:
    framework: meta/mir.framework
  mir-run:
    bin-path: bin/mir-run
  system-compositor:
    apparmor-profile: meta/apparmor.profile
