name: @PACKAGE@
version: @VERSION@
architecture: @ARCH@
type: framework
services:
  - name: system-compositor
    description: "system compositor"
    start: bin/server
    security-template: unconfined
