name: @PACKAGE@
version: @VERSION@
vendor: Mir team <mir-devel@lists.ubuntu.com>
source: http://launchpad.net/mir
architecture: @ARCH@
type: framework
services:
  - name: system-compositor
    description: "system compositor"
    start: bin/server
    security-policy:
        apparmor: ./meta/mir.apparmor
        seccomp: ./meta/mir.seccomp
binaries:
  -name: mir_demo_server
    exec: debs/usr/bin/mir_demo_server
    security-policy:
        apparmor: ./meta/mirdemosvr.apparmor
        seccomp: ./meta/mirdemosvr.seccomp
