#ifndef UBUNTU_APPLICATION_UI_WINDOW_TYPE_H_
#define UBUNTU_APPLICATION_UI_WINDOW_TYPE_H_

typedef enum
{
	U_NORMAL_WINDOW,
	U_UTILITY_WINDOW,
	U_DIALOG_WINDOW,
	U_OVERLAY_WINDOW,
	U_FREESTYLE_WINDOW,
	U_POPOVER_WINDOW
} UApplicationUiWindowType;

#endif /* UBUNTU_APPLICATION_UI_WINDOW_TYPE_H_ */